{hch 2011.05.25 区别政府, 卫生行业}
{政府财务}
{$IFDEF ZF}
  GszRelease := '政府财务';
{$ENDIF}

{卫生财务}
{$IFDEF WS}
  GszRelease := '卫生财务';
{$ENDIF}

{教育财务}
{$IFDEF JY}
  GszRelease := '教育财务';
{$ENDIF}

{社保财务}
{$IFDEF SB}
  GszRelease := '社保财务';
{$ENDIF}

{行政事业财务}
{$IFDEF XZ}
  GszRelease := '行政事业财务';
{$ENDIF}



{财政}
{$IFDEF CZ}
  GszRelease := '财政';
{$ENDIF}

{乡镇财政}
{$IFDEF XC}
  GszRelease := '乡镇财政';
{$ENDIF}


{$IFDEF G}
  GszEdition := 'G';
{$ENDIF}

{$IFDEF B}
  GszEdition := 'B';
{$ENDIF}

{$IFDEF C}
  GszEdition := 'C';
{$ENDIF}
